### ISSUE TITLE
How to integrate into an iOS project

### ISSUE THREAD

**Issue by tungdx** [aperedera/SwiftZSTD#1]
Thanks for creating this library. Could you please write down some guideline to integrate this project into an iOS project? Or it would be great if it is published on CocoaPods. Thank you in advance!

**Comment by aperedera** [comment]
Hi,

Thank you for your interest and feedback.

I've been quite busy with my day job and other things lately, but will
definitely look into providing more instructions and possibly putting it
on CocoaPods.

BTW, integrating a project like this into an iOS project should be quite
easy, there is a lot of info about it on the web.

Best Regards,

Anatoli

**Comment by tungdx** [comment]
Fortunately, I have managed to integrate it (I have not much experience with iOS development). It would be great if you could have some time to put it on CocoaPods.

Once again, thank you very much!
Best wishes.
